In [ ]:
#https://www.geeksforgeeks.org/numpy-meshgrid-function/

In [ ]:
'''
The numpy.meshgrid function is used to create a rectangular grid out of two given one-dimensional arrays 
representing the Cartesian indexing or Matrix indexing. Meshgrid function is somewhat inspired from MATLAB.
Consider the above figure with X-axis ranging from -4 to 4 and Y-axis ranging from -5 to 5. 
So there are a total of (9 * 11) = 99 points marked in the figure each with a X-coordinate and a Y-coordinate. 
For any line parallel to the X-axis, the X-coordinates of the marked points respectively are -4, -3, -2, -1, 
0, 1, 2, 3, 4. On the other hand, for any line parallel to the Y-axis, the Y-coordinates of the marked points 
from bottom to top are -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5. 
The numpy.meshgrid function returns two 
2-Dimensional arrays representing the X and Y coordinates of all the points. 

'''

In [1]:
import numpy as np

In [2]:
x = np.linspace(-4, 4, 9)
y = np.linspace(-5, 5, 11)

x_1, y_1 = np.meshgrid(x, y)

print(x_1)
print(y_1)

[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]
