In [1]:
import pandas as pd

In [11]:
import numpy as np 

In [2]:
A = pd.Series([2,4,6], index = [0,1,2])
A

0    2
1    4
2    6
dtype: int64

In [3]:
B = pd.Series([1,3,5], index = [1,2,3])
B

1    1
2    3
3    5
dtype: int64

In [4]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [6]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [15]:
rng = np.random.default_rng(42)
A1 = pd.DataFrame(rng.integers(0,20, (2,2)), columns = ['A', 'B'])
A1

A   B
0   1  15
1  13   8

In [20]:
A1.values.mean()

9.25

In [16]:
B1 = pd.DataFrame(rng.integers(0,10, (3,3)), columns = ['A', 'B', 'C'])
B1

A  B  C
0  4  8  0
1  6  2  0
2  5  9  7

In [17]:
A1 + B1

A     B   C
0   5.0  23.0 NaN
1  19.0  10.0 NaN
2   NaN   NaN NaN

In [22]:
A1.add(B1, fill_value = A1.values.mean())

A      B      C
0   5.00  23.00   9.25
1  19.00  10.00   9.25
2  14.25  18.25  16.25

In [23]:
C = rng.integers(10, size = (3,4))
C

array([[7, 7, 7, 5],
       [1, 8, 4, 5],
       [3, 1, 9, 7]])

In [24]:
C[0]

array([7, 7, 7, 5])

In [25]:
C - C[0]

array([[ 0,  0,  0,  0],
       [-6,  1, -3,  0],
       [-4, -6,  2,  2]])

In [26]:
df = pd.DataFrame(C, columns = ['q','r','s','t'])
df 

q  r  s  t
0  7  7  7  5
1  1  8  4  5
2  3  1  9  7

In [27]:
#iloc - implicit index , operate row wise 
df.iloc[0]

q    7
r    7
s    7
t    5
Name: 0, dtype: int64

In [28]:
df - df.iloc[0]

q  r  s  t
0  0  0  0  0
1 -6  1 -3  0
2 -4 -6  2  2

In [29]:
df['r']

0    7
1    8
2    1
Name: r, dtype: int64

In [31]:
df

q  r  s  t
0  7  7  7  5
1  1  8  4  5
2  3  1  9  7

In [30]:
df.subtract(df['r'], axis = 0)

q  r  s  t
0  0  0  0 -2
1 -7  0 -4 -3
2  2  0  8  6

In [33]:
df 

q  r  s  t
0  7  7  7  5
1  1  8  4  5
2  3  1  9  7

In [41]:
df.iloc[0,0:4:2]

q    7
s    7
Name: 0, dtype: int64

In [32]:
#iloc - implicit index
df.iloc[0]

q    7
r    7
s    7
t    5
Name: 0, dtype: int64

In [34]:
df.iloc[0, ::2]

q    7
s    7
Name: 0, dtype: int64