In [1]:
import numpy as np

In [2]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [5]:
name = ['alice', 'bob', 'cathy', 'doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [4]:
data = np.zeros(4, dtype = {'names': ('name', 'age', 'weight'),
                           'formats':('U10', 'i4', 'f8')})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [6]:
data['name'] = name
data ['age'] = age 
data ['weight'] = weight 

In [7]:
data 

array([('alice', 25, 55. ), ('bob', 45, 85.5), ('cathy', 37, 68. ),
       ('doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [8]:
#get all names 
data ['name']

array(['alice', 'bob', 'cathy', 'doug'], dtype='<U10')

In [9]:
#get first row of data
data[0]

('alice', 25, 55.)

In [10]:
#get name from last row
data[-1]['name']

'doug'

In [13]:
#get names where age < 30
data[data['age'] < 30]['name']

array(['alice', 'doug'], dtype='<U10')

In [14]:
b1 = np.zeros(1)
b1 

array([0.])

In [15]:
#advanced compound type:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3,3))])
x = np.zeros(1, dtype = tp)
x

array([(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
      dtype=[('id', '<i8'), ('mat', '<f8', (3, 3))])

In [16]:
x[0]

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])

In [18]:
x['id']

array([0])

In [17]:
x['mat']

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])