In [1]:
import numpy as np

In [2]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [3]:
x

array([2, 1, 4, 3, 5])

In [5]:
#sorts in place
x.sort()
x

array([1, 2, 3, 4, 5])

In [6]:
x

array([1, 2, 3, 4, 5])

In [8]:
#argsort
x1 = np.array([2,1,4,3,5])
print(np.sort(x))
i = np.argsort(x1)#returns indices of sorted elements 
i

[1 2 3 4 5]


array([1, 0, 3, 2, 4])