In [1]:
import numpy as np
import pandas as pd

In [2]:
#bad way
index = [('Cali', 2010), ('Cali', 2020),
         ('NY', 2010), ('NY', 2020), 
         ('Texas', 2010), ('Texas', 2020)]

population = [100, 200,
             300, 400,
             500, 600]

In [3]:
pop = pd.Series(population, index = index)
pop

(Cali, 2010)     100
(Cali, 2020)     200
(NY, 2010)       300
(NY, 2020)       400
(Texas, 2010)    500
(Texas, 2020)    600
dtype: int64

In [4]:
index

[('Cali', 2010),
 ('Cali', 2020),
 ('NY', 2010),
 ('NY', 2020),
 ('Texas', 2010),
 ('Texas', 2020)]

In [5]:
#better way
#create multiindex

index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([( 'Cali', 2010),
            ( 'Cali', 2020),
            (   'NY', 2010),
            (   'NY', 2020),
            ('Texas', 2010),
            ('Texas', 2020)],
           )

In [6]:
#reindex
pop = pop.reindex(index)
pop

Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [13]:
#get population for 2020
pop[:,2020]

Cali     200
NY       400
Texas    600
dtype: int64

In [14]:
#unstack : converts multi indexed series into standard indexed dataframe
pop_df = pop.unstack()
pop_df

2010  2020
Cali    100   200
NY      300   400
Texas   500   600

In [15]:
#stack : converts standard dataframe to multi indexed series
pop_df.stack()

Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [16]:
pop

Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [17]:
new_df = pd.DataFrame({'total': pop,
                      'under18': [10,20,30,40,50,60]})
new_df 

total  under18
Cali  2010    100       10
      2020    200       20
NY    2010    300       30
      2020    400       40
Texas 2010    500       50
      2020    600       60

In [19]:
pop_under18 = new_df['under18']/new_df['total']
pop_under18

Cali   2010    0.1
       2020    0.1
NY     2010    0.1
       2020    0.1
Texas  2010    0.1
       2020    0.1
dtype: float64

In [20]:
pop_under18.unstack()

2010  2020
Cali    0.1   0.1
NY      0.1   0.1
Texas   0.1   0.1

In [21]:
#methods of multiindex creation
#1) pass a list of 2 or more index arrays 
df1 = pd.DataFrame(np.random.rand(4,2), index = [['a','a','b','b'], [1,2,1,2]], columns = ['c1', 'c2'])
df1

c1        c2
a 1  0.952670  0.461320
  2  0.342126  0.049651
b 1  0.502687  0.820897
  2  0.060188  0.473570

In [22]:
#pass a dict with tuples as keys
data = {
    ('Cali', 2010):100,
    ('Cali', 2020):200,
    ('NY', 2010):300,
    ('NY', 2020):400
}
pd.Series(data)


Cali  2010    100
      2020    200
NY    2010    300
      2020    400
dtype: int64

In [23]:
#explicit multiindex constructor
pd.MultiIndex.from_arrays([['a','a','b','b'], [1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [24]:
#list of tuples
pd.MultiIndex.from_tuples([('a',1), ('a',2), ('b',1), ('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [25]:
#multilevel index names 
pop

Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [27]:
#name levels of the Multiindex
pop.index.names = ['state', 'year']
pop

state  year
Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [28]:
#multiindex for columns
#hierarchial index
index1 = pd.MultiIndex.from_product([[2013, 2014], [1,2]], names = ['year','visit'])
index1

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [29]:
#hierarchial col
cols = pd.MultiIndex.from_product([['bob', 'guido', 'sue'],
                                 ['hr', 'temp']],
                                 names = ['subject', 'type'])
cols 

MultiIndex([(  'bob',   'hr'),
            (  'bob', 'temp'),
            ('guido',   'hr'),
            ('guido', 'temp'),
            (  'sue',   'hr'),
            (  'sue', 'temp')],
           names=['subject', 'type'])

In [30]:
np.random.randn(4,6)

array([[ 0.32644173, -1.00393533, -0.01749009, -0.27661766,  1.16709168,
         0.21919469],
       [ 0.50702955, -0.40693245, -1.36180225,  0.0833853 , -0.44287215,
        -0.33718594],
       [ 1.87770195, -0.18746954, -0.20106851, -0.10223557,  1.69127046,
         0.49692065],
       [ 1.03295198, -2.26835217,  1.27909595, -1.61794691, -0.94957172,
         0.13968844]])

In [34]:
data = np.round(np.random.randn(4,6),1)
data

array([[-0.8, -0.2,  0. ,  2.4, -1.2,  1. ],
       [-0.6, -2. , -1.7,  0.8, -0.8,  1. ],
       [-0.7,  0.4,  1.7,  0.2,  0.1, -0.5],
       [-0.5,  0.3,  0. ,  2.6,  0. , -2. ]])

In [35]:
data[:,::2]

array([[-0.8,  0. , -1.2],
       [-0.6, -1.7, -0.8],
       [-0.7,  1.7,  0.1],
       [-0.5,  0. ,  0. ]])

In [36]:
data[:,::2] *= 10
data

array([[ -8. ,  -0.2,   0. ,   2.4, -12. ,   1. ],
       [ -6. ,  -2. , -17. ,   0.8,  -8. ,   1. ],
       [ -7. ,   0.4,  17. ,   0.2,   1. ,  -0.5],
       [ -5. ,   0.3,   0. ,   2.6,   0. ,  -2. ]])

In [37]:
data[:,::2]

array([[ -8.,   0., -12.],
       [ -6., -17.,  -8.],
       [ -7.,  17.,   1.],
       [ -5.,   0.,   0.]])

In [38]:
data

array([[ -8. ,  -0.2,   0. ,   2.4, -12. ,   1. ],
       [ -6. ,  -2. , -17. ,   0.8,  -8. ,   1. ],
       [ -7. ,   0.4,  17. ,   0.2,   1. ,  -0.5],
       [ -5. ,   0.3,   0. ,   2.6,   0. ,  -2. ]])

In [39]:
data += 37
data

array([[29. , 36.8, 37. , 39.4, 25. , 38. ],
       [31. , 35. , 20. , 37.8, 29. , 38. ],
       [30. , 37.4, 54. , 37.2, 38. , 36.5],
       [32. , 37.3, 37. , 39.6, 37. , 35. ]])

In [41]:
#create df : 4D data
#dimensions : subject, type, year, visit
health_data = pd.DataFrame(data, index=index1, columns=cols)
health_data


subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      29.0  36.8  37.0  39.4  25.0  38.0
     2      31.0  35.0  20.0  37.8  29.0  38.0
2014 1      30.0  37.4  54.0  37.2  38.0  36.5
     2      32.0  37.3  37.0  39.6  37.0  35.0

In [42]:
#get health data for a person
health_data['bob']

type          hr  temp
year visit            
2013 1      29.0  36.8
     2      31.0  35.0
2014 1      30.0  37.4
     2      32.0  37.3

In [44]:
index

MultiIndex([( 'Cali', 2010),
            ( 'Cali', 2020),
            (   'NY', 2010),
            (   'NY', 2020),
            ('Texas', 2010),
            ('Texas', 2020)],
           names=['state', 'year'])

In [45]:
cols

MultiIndex([(  'bob',   'hr'),
            (  'bob', 'temp'),
            ('guido',   'hr'),
            ('guido', 'temp'),
            (  'sue',   'hr'),
            (  'sue', 'temp')],
           names=['subject', 'type'])

In [48]:
#create df - 4D data 
health_data = pd.DataFrame(data, index=index1, columns=cols)
health_data
#dimensions : subject, type, year, visit

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      24.0  36.8  21.0  36.4  28.0  35.7
     2      28.0  37.5  29.0  36.9  16.0  36.2
2014 1      19.0  38.4  21.0  37.3  48.0  37.9
     2      33.0  36.7  57.0  37.7  46.0  37.1

In [49]:
#health data for guido
health_data['guido']

type          hr  temp
year visit            
2013 1      21.0  36.4
     2      29.0  36.9
2014 1      21.0  37.3
     2      57.0  37.7

In [53]:
#heart rate data for guido 
health_data['guido']['hr']

year  visit
2013  1        21.0
      2        29.0
2014  1        21.0
      2        57.0
Name: hr, dtype: float64

In [54]:
#or
health_data['guido', 'hr']

year  visit
2013  1        21.0
      2        29.0
2014  1        21.0
      2        57.0
Name: (guido, hr), dtype: float64

In [55]:
health_data

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      24.0  36.8  21.0  36.4  28.0  35.7
     2      28.0  37.5  29.0  36.9  16.0  36.2
2014 1      19.0  38.4  21.0  37.3  48.0  37.9
     2      33.0  36.7  57.0  37.7  46.0  37.1

In [56]:
health_data.iloc[:2, :2]

subject      bob      
type          hr  temp
year visit            
2013 1      24.0  36.8
     2      28.0  37.5

In [44]:
health_data.loc[:,('bob','hr')]

year  visit
2013  1        29.0
      2        31.0
2014  1        30.0
      2        32.0
Name: (bob, hr), dtype: float64

In [43]:
health_data

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      29.0  36.8  37.0  39.4  25.0  38.0
     2      31.0  35.0  20.0  37.8  29.0  38.0
2014 1      30.0  37.4  54.0  37.2  38.0  36.5
     2      32.0  37.3  37.0  39.6  37.0  35.0

In [45]:
#get heart rate data for all 3 - did not understand
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'hr']]

subject      bob guido   sue
type          hr    hr    hr
year visit                  
2013 1      29.0  37.0  25.0
2014 1      30.0  54.0  38.0

In [ ]:
#Rearranging Multi-indexes 

In [73]:
index = pd.MultiIndex.from_product([['a','c','b'], [1,2]]) # a b c need to be sorted or you will get error
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.177556
      2      0.833876
c     1      0.900113
      2      0.158716
b     1      0.271595
      2      0.390270
dtype: float64

In [74]:
#take partial slice
data['a'][1]

0.17755576896359104

In [71]:
#take partial slice
#data['a':'b']

In [72]:
#sort index (alphabatically)
data = data.sort_index()
data

char  int
a     1      0.972966
      2      0.802163
b     1      0.212404
      2      0.629728
c     1      0.935900
      2      0.878996
dtype: float64

In [ ]:
#stacking and unstacking indices

In [76]:
pop

state  year
Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [77]:
pop.unstack()

year   2010  2020
state            
Cali    100   200
NY      300   400
Texas   500   600

In [78]:
pop.unstack(level=0)

state  Cali   NY  Texas
year                   
2010    100  300    500
2020    200  400    600

In [79]:
pop.unstack(level=1)

year   2010  2020
state            
Cali    100   200
NY      300   400
Texas   500   600

In [ ]:
#index setting and resetting

In [80]:
pop

state  year
Cali   2010    100
       2020    200
NY     2010    300
       2020    400
Texas  2010    500
       2020    600
dtype: int64

In [82]:
# turn index labels into columns
#optionally specify name of the data for column representation
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0   Cali  2010         100
1   Cali  2020         200
2     NY  2010         300
3     NY  2020         400
4  Texas  2010         500
5  Texas  2020         600

In [83]:
#Build multiindex from columns
pop_flat.set_index(['state', 'year'], population)

/var/folders/jy/j1v16kdn0ws9wkysn8s1zw540000gn/T/ipykernel_61077/4125988986.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only
  pop_flat.set_index(['state', 'year'], population)


population
state year            
Cali  2010         100
      2020         200
NY    2010         300
      2020         400
Texas 2010         500
      2020         600