In [2]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701)
x = rng.integers(100,size = 10)
x

array([90, 40,  9, 30, 80, 67, 39, 15, 33, 79])

In [3]:
#Access 3 diff elements
[x[3], x[7], x[2]]

[30, 15, 9]

In [4]:
#or 
ind = [3,7,2]
x[ind]

array([30, 15,  9])

In [6]:
ind2 = np.array([[3,7],
                [4,5]])
x[ind2]

array([[30, 15],
       [80, 67]])

In [8]:
#multiple dimensions
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
row = np.array([0,1,2])
print(row)
col = np.array([2,1,3])
print(col)

[0 1 2]
[2 1 3]


In [11]:
X[row, col] # X[0,2] X[1,1] X[2,3]

array([ 2,  5, 11])

In [12]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [15]:
row

array([0, 1, 2])

In [14]:
row.shape

(3,)

In [16]:
row.reshape(3,1)

array([[0],
       [1],
       [2]])

In [13]:
row[:,np.newaxis].shape


(3, 1)

In [17]:
X[row[:,np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [18]:
col.shape

(3,)

In [19]:
mask = np.array([True, False, True, False])
print(mask)
print(mask.shape)

[ True False  True False]
(4,)


In [ ]:
#modify values with fancy indexing

In [3]:
x = np.arange(10)
print(x)
i = np.array([2,1,8,4])
print(i)

[0 1 2 3 4 5 6 7 8 9]
[2 1 8 4]


In [4]:
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [5]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [6]:
y = np.zeros(10)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
y[0] = 6
print(y)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
i1 = [2,3,3,4,4,4]
print(x)
print(x[i1])

[ 0 89 89  3 89  5  6  7 89  9]
[89  3  3 89 89 89]


In [10]:
x[i1] +=1
x

array([ 0, 89, 90,  4, 90,  5,  6,  7, 89,  9])