In [2]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
lst = list(range(5))
nd_array = np.array(lst)
nd_array

array([0, 1, 2, 3, 4])

In [3]:
# int was upcast to float as numpy arrays can only have data of same data type
lst_2 = [2.34,8.97,4,6]
nd_array_2 = np.array(lst_2)
nd_array_2

array([2.34, 8.97, 4.  , 6.  ])

In [4]:
np_array = np.array([1,2,3,4], dtype = np.float32)
np_array

array([1., 2., 3., 4.], dtype=float32)

In [3]:
#multi dimensional array
#inner list is treated as a row in the resulting 2D array
np_array_2 = np.array([range(i, i+3) for i in (2,4,6)])
np_array_2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
np_array_2.shape

(3, 3)

In [5]:
np_array_2.ndim

2

In [9]:
#Creating Arrays from scratch

In [11]:
#length 10 array filled with zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#3x5 floating array filled with 1s
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#3x5 floating array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
#array with a linear sequence starting with 0, ending at 20, step 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#array with 5 values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#3x3 array of uniformily distributed values between 0 and 1
#0.0 <= x < 1.0
np.random.random((3,3))

array([[0.36042365, 0.50459062, 0.30427352],
       [0.08367482, 0.93342366, 0.76643414],
       [0.03380631, 0.37816333, 0.45290072]])

In [19]:
#3x3 array of normally distributed values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.9081008 , -0.4951167 , -0.33789368],
       [ 0.66460166, -1.67534377,  0.15631928],
       [ 1.00090725,  1.11756221,  0.16685627]])

In [20]:
#3x3 array of random integers in half interval (0,10]
np.random.randint(0,10,(3,3))

array([[0, 0, 2],
       [3, 4, 1],
       [8, 4, 0]])

In [23]:
#3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#uninitialised array of 3 ints , values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])