In [1]:
import numpy as np

In [ ]:
#numpy array attributes

In [2]:
rng = np.random.default_rng(seed=1701)

In [3]:
#one dim array
x1 = rng.integers(10, size = 6)
x1

array([9, 4, 0, 3, 8, 6])

In [4]:
#2 dim array
x2 = rng.integers(10, size = (3,4))
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [5]:
#3 dim array
x3 = rng.integers(10, size = (3,4,5))
x3

array([[[4, 3, 5, 5, 0],
        [8, 3, 5, 2, 2],
        [1, 8, 8, 5, 3],
        [0, 0, 8, 5, 8]],

       [[5, 1, 6, 2, 3],
        [1, 2, 5, 6, 2],
        [5, 2, 7, 9, 3],
        [5, 6, 0, 2, 0]],

       [[2, 9, 4, 3, 9],
        [9, 2, 2, 4, 0],
        [0, 3, 0, 0, 2],
        [3, 2, 7, 4, 7]]])

In [7]:
print("x3 ndim : " ,x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)
print("x3 dtype : ", x3.dtype)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60
x3 dtype :  int64


In [ ]:
#Reshaping arrays :

In [8]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [11]:
y.reshape(1,3)

array([[1, 2, 3]])

In [14]:
#same as reshape 1,3
y[np.newaxis,:]

array([[1, 2, 3]])

In [12]:
y.reshape(3,1)

array([[1],
       [2],
       [3]])

In [15]:
#same as reshape(3,1)
y[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [16]:
arr = np.arange(5*5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.shape

(25,)

In [20]:
a1 = arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
a1.shape

(5, 5)

In [26]:
#add dimension
a1[np.newaxis].shape

(1, 5, 5)

In [22]:
arr_5d = a1[np.newaxis,...,np.newaxis,np.newaxis]
arr_5d.shape

(1, 5, 5, 1, 1)

In [19]:
arr.reshape(5,5).shape

(5, 5)

In [17]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Array concatenation

In [ ]:
#1D arrays

In [28]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [29]:
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#2D arrays

In [33]:
arr_2d = np.array([range(i,i+3) for i in (1,4)])
arr_2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr_2d.shape

(2, 3)

In [35]:
arr_2d.ndim

2

In [37]:
#concatenate along row
c_r = np.concatenate([arr_2d, arr_2d])
c_r

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
c_r.ndim

2

In [39]:
c_r.shape

(4, 3)

In [40]:
#concatenate along col
c_c = np.concatenate([arr_2d, arr_2d], axis=1)
c_c

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
c_c.ndim

2

In [42]:
c_c.shape

(2, 6)

In [ ]:
#arrays of mixed dims :

In [ ]:
#vertical stack (vertically stack the arrays) - np.vstack and 
#horizontal stack (horizontally stack the arrays) = no.hstack

In [43]:
x

array([1, 2, 3])

In [51]:
x.ndim

1

In [56]:
x.shape

(3,)

In [44]:
arr_2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr_2d.ndim

2

In [57]:
arr_2d.shape

(2, 3)

In [46]:
np.vstack([x,arr_2d])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
arr_99 = np.array([[99],[99]])
arr_99

array([[99],
       [99]])

In [54]:
arr_99.ndim

2

In [58]:
arr_99.shape

(2, 1)

In [55]:
np.hstack([arr_2d, arr_99])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [ ]:
#Splitting arrays

In [59]:
sp = np.arange(9.0)
sp

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [62]:
np.split(sp,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [63]:
np.split(sp,5)

ValueError: array split does not result in an equal division

In [64]:
np.array_split(sp,5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [65]:
sp_8 = np.arange(8.0)
sp_8

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [66]:
np.split(sp_8, [3,5])

[array([0., 1., 2.]), array([3., 4.]), array([5., 6., 7.])]

In [67]:
np.split(sp_8, [3,5,7])

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7.])]

In [68]:
np.split(sp_8, [3,5,7,9])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5., 6.]),
 array([7.]),
 array([], dtype=float64)]

In [70]:
grid = np.arange(16)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
grid_r = grid.reshape(4,4)
grid_r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper, lower = np.vsplit(grid_r,2)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left, right = np.hsplit(grid_r,2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
