In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701)

In [4]:
values = rng.integers(1,10, size = 5)
values

array([9, 4, 1, 3, 8])

In [12]:
rng = np.random.default_rng(seed=1701)
def compute_reciprocal(values):
    output = np.empty(len(values)) 
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1,10, size = 5)
print(compute_reciprocal(values))
%timeit compute_reciprocal(values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
7.8 µs ± 56.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
big_array = rng.integers(1,10, size = 100000)
print(compute_reciprocal(big_array))
%timeit compute_reciprocal(big_array)

[0.14285714 0.25       0.5        ... 1.         1.         0.14285714]
141 ms ± 665 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%timeit (1.0/values)

806 ns ± 2.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit (1.0/big_array) #faster than 141 ms (python loop)

58.3 µs ± 60.9 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [18]:
np.arange(5)/ np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [19]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])